# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MBF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreastFed',
            fields=[
                ('babyevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MBF.BabyEvent')),
                ('breast', models.CharField(choices=[('LT', 'Left'), ('RT', 'Right')], default='LT', max_length=2)),
            ],
            bases=('MBF.babyevent',),
        ),
    ]
