# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MBF', '0003_bottlefed_diaperstatus_sleep_temperature_wake'),
    ]

    operations = [
        migrations.AddField(
            model_name='babyevent',
            name='baby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MBF.Baby'),
        ),
    ]
