# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MBF', '0005_baby_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='caretaker',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MBF.Family'),
        ),
    ]
