# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBF', '0007_auto_20160618_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfed',
            name='breast',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5),
        ),
        migrations.AlterField(
            model_name='diaperstatus',
            name='diaper',
            field=models.CharField(choices=[('poo', 'Poo'), ('pee', 'Pee'), ('both', 'Poo & Pee')], default='pee', max_length=4),
        ),
    ]
