# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MBF', '0008_auto_20160618_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBF.Family')),
            ],
        ),
    ]
