# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MBF', '0009_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='MBF.Family'),
        ),
    ]
