# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBF', '0010_auto_20160619_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='family',
        ),
        migrations.AlterField(
            model_name='diaperstatus',
            name='diaper',
            field=models.CharField(choices=[('poo', 'Poo'), ('pee', 'Pee'), ('poo & pee', 'Poo & Pee')], default='pee', max_length=4),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
