# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBF', '0011_auto_20160621_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaperstatus',
            name='diaper',
            field=models.CharField(choices=[('poo', 'Poo'), ('pee', 'Pee'), ('poo & pee', 'Poo & Pee')], default='pee', max_length=9),
        ),
    ]
